name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Test code
        run: python3 ./test.py
      - name: Display Python version
        run: python -c "import sys; print(sys.version)" >> ./result${{ matrix.python-version }}.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: my-artifact
          path: ./result.txt

